### ISSUE TITLE
no infinite

### ISSUE THREAD

**Issue by bubudrc** [ltebean/LTInfiniteScrollView#10]
I tried to create a scroll like your example, but never be infinite... go from view 0 to last one and the scroll stop.

Your example has the same error

**Comment by ltebean** [comment]
Originally, this lib makes the index in the center 0, the whole scroll view is like:   -9999....|-1 0 1|...9999, if you set numberOfTotalViews to a very big number, the scrollView will act as an infinite scroll view. However, it is not very easy to use in most cases. So in the newest version, I made the most left index 0. the scroll view becomes like: 0 1 |2 3 4| 5 6, actually you can set the numberOfTotalViews to a very big number, and set the initial index to numberOfTotalViews / 2, the it will become like:    0...  |99 100 101|...199, acting as an infinite scroll view

**Comment by ltebean** [comment]
Actually it is not very proper to call it infinite scroll view now, although you can achieve the infinite behavior by setting the numberOfTotalViews to a very big number. The ease that this lib offer is horizental pagination and animation
