### ISSUE TITLE
Can't scroll to the end

### ISSUE THREAD

**Issue by werne2j** [ltebean/LTInfiniteScrollView#11]
I set the number of views to 20 in the task switcher demo and it does not scroll to the end. It bounces back to the 3rd to last view and leaves 2 views behind it.

![feb 09 2016 11 59](https://cloud.githubusercontent.com/assets/5973248/12923676/97aa45f2-cf24-11e5-8b08-28cc9f4f654c.gif)

**Comment by ltebean** [comment]
in v4.1.0 it allows to set the contentInset of the internal scrollView, thus the problem can be fixed, you can pull the latest code to see the updated demo, thanks!

**Comment by werne2j** [comment]
Works perfectly! Great Job!
