### ISSUE TITLE
Scroll problem when number of Views is even number

### ISSUE THREAD

**Issue by jacks8x** [ltebean/LTInfiniteScrollView#2]
Change in the file DemoViewController.m in your demo code like below:
# define NUMBER_OF_VISIBLE_VIEWS 1

....
- (NSInteger)numberOfViews
  {
  return 4;
  }
  It displays incorrect : display 5 views instead 4, and the first and last view just can scroll to a half of its view

**Comment by ltebean** [comment]
fixed in v2.1.0
